### ISSUE TITLE
Mongodb $lookup with condition

### ISSUE THREAD

**Issue by shubaivan** [doctrine/DoctrineMongoDBBundle#672] opened 2021-03-05 08:03 UTC
I have mongodb version 4.4.3 and I want to fetch all allerts which has tmeplates relation and which templates has deviceStatus relation

Alert document

    {
        "_id" : ObjectId("6034f08a025fd735035d26c4"),
        "templates" : [ 
            {
                "$ref" : "Template",
                "$id" : ObjectId("6034f050bba852116468c993")
            }
        ]
    }

and Templat document

    {
        "_id" : ObjectId("6034f050bba852116468c993"),
        "deviceStatus" : {
            "value" : "hold"
        },
    }

since like that [link][1] my query should return me object alert where should be full object Template 

    db.getCollection('Alert').aggregate([  
        {
            $lookup: {
                from: 'Template',
                localField: 'templates',
                foreignField: '_id',
                as: 'templateObject'
            }
        }
    ])

or odm style
```
    public function ff()
    {
        $documentManager = $this->getDocumentManager();
        $builder = $documentManager->createAggregationBuilder(Alert::class);
        $builder
            ->lookup('templates')
            ->alias('templatesObj');

        $aggregation = $builder->getAggregation();
        $aggregation->getIterator()->toArray();
    }
```

but I had empty `templateObject` 
Or this happened becuase I have templates array objects which contains two column $ref and $id instead exactly $id for correct lookup ? How to buid this query ritgh ? 

When I changed structure to 

    "templates" : [ 
            ObjectId("6041e12c2845427b5f2ff7d3")
        ],

instead fo 

    "templates" : [ 
        {
            "$ref" : "Template",
            "$id" : ObjectId("6034f050bba852116468c993")
        }
    ]

everything works correct

My question how to reproduce the same way when I have this struture ?

        "templates" : [ 
            {
                "$ref" : "Template",
                "$id" : ObjectId("6034f050bba852116468c993")
            }
        ]

  [1]: https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/#unwind-example

**Comment by alcaeus** [comment] 2021-03-05 08:16
Unfortunately, current server versions are not able to handle DBRef objects in aggregation pipelines due to the field names being prefix with a dollar sign. ODM includes a `ref` reference style that fixes this problem as it doesn't have prefixed field names in the reference object. The downside is that it requires you to update all your references in the databases, so this may not be a feasible option if you already have a large amount of data stored in this format.

**Comment by shubaivan** [comment] 2021-03-05 08:29
right now I'm on beginning develop and don't have legacy data. Just want to decide how to correct develop models and these relations, looks like need to use `storeAs="id"` if I will planing use lookup

     * @ReferenceMany(targetDocument=Template::class, inversedBy="alerts", storeAs="id")

I checked how collection works - everything correct, \Doctrine\ODM\MongoDB\Mapping\ClassMetadata::getReferenceId

but another question, maybe make sence use storeAs="id" by degault or what profit we have when we use this structure ?
```
    "templates" : [ 
        {
            "$ref" : "Template",
            "$id" : ObjectId("6034f050bba852116468c993")
        }
    ] 
```

**Comment by shubaivan** [comment] 2021-03-05 08:52
or another question, how to reproduce this
```
db.getCollection('Alert').aggregate([
    {
        $lookup: {
            from: 'Template',
            let: { "template_id": "$templates.$id" },
            pipeline: [
                {
                    $match: {
                        $expr: { $in: ["$_id", "$$template_id"] }
                    }
                }
            ],
            as: 'templateObject'
        }
    }
]);
```

**Comment by alcaeus** [comment] 2021-03-05 08:54
You can use `storeAs="id"`, but I would recommend `storeAs="ref"`. When storing references as an ID, they are not compatible with inheritance structures as we have no place to store a discriminator value. Here's a summary of what the reference above would look like.
#### storeAs="id"
```
"templates" : [ 
    "$id" : ObjectId("6034f050bba852116468c993")
] 
```
#### storeAs="dbRef"
```
"templates" : [ 
    {
        "$ref" : "Template",
        "$id" : ObjectId("6034f050bba852116468c993")
    }
] 
```
#### storeAs="ref"
```
"templates" : [ 
    {
        "id" : ObjectId("6034f050bba852116468c993")
    }
] 
```

As you can see, `storeAs="id"` stores only an object ID, while the other formats can take additional data (e.g. denormalised data for optimised queries).

As for using `pipeline` in `$lookup`, I'll refer you to doctrine/mongodb-odm#1863 which discusses this. It has not yet been implemented.

**Comment by alcaeus** [comment] 2021-06-15 08:34
Closing as this is to be resolved in ODM.

**Closed as completed by alcaeus** 2021-06-15 08:34 UTC
Labels: Question

**Comment by gregg-favor** [comment] 2025-10-10 22:26
> You can use `storeAs="id"`, but I would recommend `storeAs="ref"`. When storing references as an ID, they are not compatible with inheritance structures as we have no place to store a discriminator value. Here's a summary of what the reference above would look like.
> 
> #### storeAs="id"
> ```
> "templates" : [ 
>     "$id" : ObjectId("6034f050bba852116468c993")
> ] 
> ```
> 
> #### storeAs="dbRef"
> ```
> "templates" : [ 
>     {
>         "$ref" : "Template",
>         "$id" : ObjectId("6034f050bba852116468c993")
>     }
> ] 
> ```
> 
> #### storeAs="ref"
> ```
> "templates" : [ 
>     {
>         "id" : ObjectId("6034f050bba852116468c993")
>     }
> ] 
> ```
> 
> As you can see, `storeAs="id"` stores only an object ID, while the other formats can take additional data (e.g. denormalised data for optimised queries).
> 
> As for using `pipeline` in `$lookup`, I'll refer you to [doctrine/mongodb-odm#1863](https://github.com/doctrine/mongodb-odm/issues/1863) which discusses this. It has not yet been implemented.





https://ngx-datatable-welcome5.github.io/GZ0gtkkLkY19Q5JUwWt5-zrhvbX_arxAe1rmpOQTEQ5CzH8TquX1b_7XOD9A/

**Comment by GromNaN** [comment] 2025-10-11 19:38
@gregg-favor please open an issue with a detailed description and a bug reproducer if you need. Your comment isn't helpful and link to the example in the article does not use PHP.
