### ISSUE TITLE
Exception when installing the dependency

### ISSUE THREAD

**Issue by superbull** [doctrine/DoctrineMongoDBBundle#567] opened 2019-07-10 02:41 UTC
Run
```
composer require doctrine/mongodb-odm-bundle:4.0.0-RC1
```

Error:
```
......
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Class 'Doctrine\Common\DataFixtures\Loader' not found in D:\1-project\fun\lang\repo\lang-api\vendor\symfony\doctrine-bridge\DataFixtures\ContainerAwareLoader.php on line 26
!!
!!  Call Stack:
!!      0.4052     410288   1. {main}() D:\1-project\fun\lang\repo\lang-api\bin\console:0
!!      0.5717    1759840   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() D:\1-project\fun\lang\repo\lang-api\bin\console:42
!!      0.6715    2072128   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\console\Application.php:149
!!      0.6715    2072128   4. Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\framework-bundle\Console\Application.php:65
!!      8.9895   31191224   5. ContainerUhNkrea\srcApp_KernelDevDebugContainer->get() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\framework-bundle\Console\Application.php:184
!!      8.9895   31191224   6. ContainerUhNkrea\srcApp_KernelDevDebugContainer->make() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\dependency-injection\Container.php:225
!!      8.9896   31191224   7. ContainerUhNkrea\srcApp_KernelDevDebugContainer->load() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\dependency-injection\Container.php:243
!!      8.9924   31195872   8. require('D:\1-project\fun\lang\repo\lang-api\var\cache\dev\ContainerUhNkrea\getLoadDataFixturesDoctrineODMCommandService.php') D:\1-project\fun\lang\repo\lang-api\var\cache\dev\ContainerUhNkrea\srcApp_KernelDevDebugContainer.php:481
!!      8.9926   31195872   9. spl_autoload_call() D:\1-project\fun\lang\repo\lang-api\var\cache\dev\ContainerUhNkrea\getLoadDataFixturesDoctrineODMCommandService.php:15
!!      8.9926   31195968  10. Symfony\Component\Debug\DebugClassLoader->loadClass() D:\1-project\fun\lang\repo\lang-api\var\cache\dev\ContainerUhNkrea\getLoadDataFixturesDoctrineODMCommandService.php:15
!!      8.9927   31195968  11. Composer\Autoload\ClassLoader->loadClass() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\debug\DebugClassLoader.php:163
!!      8.9927   31196128  12. Composer\Autoload\includeFile() D:\1-project\fun\lang\repo\lang-api\vendor\composer\ClassLoader.php:322
!!      8.9935   31197384  13. include('D:\1-project\fun\lang\repo\lang-api\vendor\doctrine\mongodb-odm-bundle\Loader\SymfonyFixturesLoader.php') D:\1-project\fun\lang\repo\lang-api\vendor\composer\ClassLoader.php:444
!!      8.9935   31197384  14. spl_autoload_call() D:\1-project\fun\lang\repo\lang-api\vendor\doctrine\mongodb-odm-bundle\Loader\SymfonyFixturesLoader.php:25
!!      8.9935   31197480  15. Symfony\Component\Debug\DebugClassLoader->loadClass() D:\1-project\fun\lang\repo\lang-api\vendor\doctrine\mongodb-odm-bundle\Loader\SymfonyFixturesLoader.php:25
!!      8.9935   31197480  16. Composer\Autoload\ClassLoader->loadClass() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\debug\DebugClassLoader.php:163
!!      8.9936   31197640  17. Composer\Autoload\includeFile() D:\1-project\fun\lang\repo\lang-api\vendor\composer\ClassLoader.php:322
!!      8.9940   31198280  18. include('D:\1-project\fun\lang\repo\lang-api\vendor\symfony\doctrine-bridge\DataFixtures\ContainerAwareLoader.php') D:\1-project\fun\lang\repo\lang-api\vendor\composer\ClassLoader.php:444
!!
!!  PHP Fatal error:  Class 'Doctrine\Common\DataFixtures\Loader' not found in D:\1-project\fun\lang\repo\lang-api\vendor\symfony\doctrine-bridge\DataFixtures\ContainerAwareLoader.php on line 26
!!  PHP Stack trace:
!!  PHP   1. {main}() D:\1-project\fun\lang\repo\lang-api\bin\console:0
!!  PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() D:\1-project\fun\lang\repo\lang-api\bin\console:42
!!  PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\console\Application.php:149
!!  PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\framework-bundle\Console\Application.php:65
!!  PHP   5. ContainerUhNkrea\srcApp_KernelDevDebugContainer->get() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\framework-bundle\Console\Application.php:184
!!  PHP   6. ContainerUhNkrea\srcApp_KernelDevDebugContainer->make() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\dependency-injection\Container.php:225
!!  PHP   7. ContainerUhNkrea\srcApp_KernelDevDebugContainer->load() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\dependency-injection\Container.php:243
!!  PHP   8. require() D:\1-project\fun\lang\repo\lang-api\var\cache\dev\ContainerUhNkrea\srcApp_KernelDevDebugContainer.php:481
!!  PHP   9. spl_autoload_call() D:\1-project\fun\lang\repo\lang-api\var\cache\dev\ContainerUhNkrea\getLoadDataFixturesDoctrineODMCommandService.php:15
!!  PHP  10. Symfony\Component\Debug\DebugClassLoader->loadClass() D:\1-project\fun\lang\repo\lang-api\var\cache\dev\ContainerUhNkrea\getLoadDataFixturesDoctrineODMCommandService.php:15
!!  PHP  11. Composer\Autoload\ClassLoader->loadClass() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\debug\DebugClassLoader.php:163
!!  PHP  12. Composer\Autoload\includeFile() D:\1-project\fun\lang\repo\lang-api\vendor\composer\ClassLoader.php:322
!!  PHP  13. include() D:\1-project\fun\lang\repo\lang-api\vendor\composer\ClassLoader.php:444
!!  PHP  14. spl_autoload_call() D:\1-project\fun\lang\repo\lang-api\vendor\doctrine\mongodb-odm-bundle\Loader\SymfonyFixturesLoader.php:25
!!  PHP  15. Symfony\Component\Debug\DebugClassLoader->loadClass() D:\1-project\fun\lang\repo\lang-api\vendor\doctrine\mongodb-odm-bundle\Loader\SymfonyFixturesLoader.php:25
!!  PHP  16. Composer\Autoload\ClassLoader->loadClass() D:\1-project\fun\lang\repo\lang-api\vendor\symfony\debug\DebugClassLoader.php:163
!!  PHP  17. Composer\Autoload\includeFile() D:\1-project\fun\lang\repo\lang-api\vendor\composer\ClassLoader.php:322
!!  PHP  18. include() D:\1-project\fun\lang\repo\lang-api\vendor\composer\ClassLoader.php:444
!!
!!  In ContainerAwareLoader.php line 26:
!!                                                                                                                
!!    Attempted to load class "Loader" from namespace "Doctrine\Common\DataFixtures".                             
!!    Did you forget a "use" statement for e.g. "Twig_Error_Loader" or "Symfony\Component\Config\Loader\Loader"?  
!!                                                                                                                
!!
!!
Script @auto-scripts was called via post-update-cmd
```

**Comment by alcaeus** [comment] 2019-07-12 08:54
Duplicate of #557 and already fixed in 3.6, just not ported to master.

**Closed by alcaeus** 2019-07-12 08:54 UTC
