### ISSUE TITLE
Symfony4 Unique constraint error

### ISSUE THREAD

**Issue by seqq** [doctrine/DoctrineMongoDBBundle#444] opened 2017-12-19 09:43 UTC
Hi, got error, when I try to add Unique constraint to yaml validator.
`App\Document\User:
    constraints:
        - Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique:
            fields: email `

`Error: Class 'doctrine_odm.mongodb.unique' not found in /var/www/vendor/symfony/validator/ConstraintValidatorFactory.php:43`

**Comment by malarzm** [comment] 2017-12-19 13:24
@seqq could you please provide a failing test case (or a fork of project where this happens)? I took a look at the configuration and the [validator is tagged](https://github.com/doctrine/DoctrineMongoDBBundle/blob/fafbb361043f4f78d4b5046b5687836c4128c83a/Resources/config/mongodb.xml#L170). Also ORM has same configuration so I take it should "just work" :)

**Comment by alcaeus** [comment] 2018-09-07 14:57
I couldn't reproduce this in my own app - I can confirm however that this issue comes up if you apply the constraint from the bridge, not the one from this bundle. Since this isn't the case and OP hasn't provided additional details, I'm closing this as `invalid`.

**Closed by alcaeus** 2018-09-07 14:57 UTC
Labels: bug, question
