### ISSUE TITLE
Command is appended to the last query on the same collection in the profiler

### ISSUE THREAD

**Issue by r1pp3rj4ck** [doctrine/DoctrineMongoDBBundle#262] opened 2014-07-28 12:33 UTC
It seems that a custom command or aggregation is appended to the last query on the same collection in the profiler. The query is executed succesfully, but it's misleading when checked in the WDT Profiler. Here is a [code snippet](https://gist.github.com/r1pp3rj4ck/dd12df4e934d518af479) that helps demonstrate the bug.

The resulting query looks like this:

    db.Post.count(
        { "domainId": 25 }
    ).runCommand(
        { "aggregate": "Post", "pipeline": [
            { "$match": { "published": { "$lt": "2014-7-24" } } },
            { "$group": { "_id": { "$dayOfYear": "$published" }, "count": { "$sum": 1 } } } 
        ]
    });

As the comment in line 12 indicates, if line 13 is removed, the query works as expected.

I reported this issue mistakenly on doctrine/mongodb-odm#919 first, because I thought the query was the faulty one itself.

**Comment by alcaeus** [comment] 2015-12-25 08:24
I apologize for the delay here. I took a look at this today and found the following:
1. If `logQuery` in the data collector is called twice, the data collector doesn't group the queries
2. In doctrine/mongodb, which is responsible for calling the query loggers, running `count()` followed by `aggregate` on a `LoggableCollection` produces two calls to `logQuery`, so point number 1 comes into play.

I'd say that this bug was fixed sometime after your ticket was created, especially since doctrine/mongodb#197 (which introduced proper logging for `aggregate` in `LoggableCollection`) was merged after your ticket was created. I'd assume this is why I can't reproduce it now. If you find that the issue still persists, please feel free to re-open this and I'll try to get to the bottom of this.

**Closed by alcaeus** 2015-12-25 08:24 UTC
Labels: bug
