### ISSUE TITLE
MongoDBTypeGuesser implements FormTypeGuesserInterface, but Symfony/Form is not a required package.

### ISSUE THREAD

**Issue by rickogden** [doctrine/DoctrineMongoDBBundle#566] opened 2019-07-09 16:25 UTC
After updating to PHP 7.3.7, the following error occurs when running the container debugger if symfony/form is not installed: 
> Fatal error: During class fetch: Uncaught ReflectionException: Class Symfony\Component\Form\FormTypeGuesserInterface not found in /path/to/project/vendor/doctrine/mongodb-odm-bundle/Form/DoctrineMongoDBTypeGuesser.php:26

Running `doctrine/mongodb-odm-bundle` v3.5.3. This could be related to this issue that was fixed: https://bugs.php.net/bug.php?id=76980

Full stack trace:
```
Fatal error: During class fetch: Uncaught ReflectionException: Class Symfony\Component\Form\FormTypeGuesserInterface not found in /path/to/project/vendor/doctrine/mongodb-odm-bundle/Form/DoctrineMongoDBTypeGuesser.php:26
Stack trace:
#0 /path/to/project/vendor/symfony/debug/DebugClassLoader.php(160): require('/path/to/proj...')
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('Doctrine\\Bundle...')
#2 [internal function]: spl_autoload_call('Doctrine\\Bundle...')
#3 /path/to/project/vendor/symfony/config/Resource/ClassExistenceResource.php(78): class_exists('Doctrine\\Bundle...')
#4 /path/to/project/vendor/symfony/dependency-injection/ContainerBuilder.php(353): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
#5 /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(336): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('Doctrine\\Bundle...', false)
#6 /Use in /path/to/project/vendor/doctrine/mongodb-odm-bundle/Form/DoctrineMongoDBTypeGuesser.php on line 26

Call Stack:
0.0038     404488   1. {main}() /path/to/project/bin/console:0
0.0886    2563920   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /path/to/project/bin/console:38
0.1048    2821000   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /path/to/project/vendor/symfony/console/Application.php:149
0.1048    2821000   4. Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() /path/to/project/vendor/symfony/framework-bundle/Console/Application.php:65
0.1048    2821000   5. App\Kernel->boot() /path/to/project/vendor/symfony/framework-bundle/Console/Application.php:159
0.1194    3215568   6. App\Kernel->initializeContainer() /path/to/project/vendor/symfony/http-kernel/Kernel.php:133
0.4648    9994680   7. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /path/to/project/vendor/symfony/http-kernel/Kernel.php:550
0.4707    9998800   8. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /path/to/project/vendor/symfony/dependency-injection/ContainerBuilder.php:756
1.2517   22194480   9. Symfony\Component\DependencyInjection\Compiler\AutowirePass->process() /path/to/project/vendor/symfony/dependency-injection/Compiler/Compiler.php:95
1.2517   22194480  10. Symfony\Component\DependencyInjection\Compiler\AutowirePass->process() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:52
1.2517   22194480  11. Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() /path/to/project/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46
1.2517   22194480  12. Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:71
1.2517   22194480  13. Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:99
1.2560   22216608  14. Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue() /path/to/project/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:82
1.2560   22216608  15. Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:71
1.2561   22216608  16. Symfony\Component\DependencyInjection\Compiler\AutowirePass->autowireCalls() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:122
1.2561   22216608  17. Symfony\Component\DependencyInjection\Compiler\AutowirePass->autowireMethod() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:172
1.2561   22218224  18. Symfony\Component\DependencyInjection\Compiler\AutowirePass->Symfony\Component\DependencyInjection\Compiler\{closure:/path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:230-242}() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:262
1.2588   22285984  19. Symfony\Component\DependencyInjection\Exception\AutowiringFailedException->__construct() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:237
1.2588   22285984  20. Symfony\Component\DependencyInjection\Compiler\AutowirePass->Symfony\Component\DependencyInjection\Compiler\{closure:/path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:384-386}() /path/to/project/vendor/symfony/dependency-injection/Exception/AutowiringFailedException.php:27
1.2588   22285984  21. Symfony\Component\DependencyInjection\Compiler\AutowirePass->createTypeNotFoundMessage() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:385
1.2595   22289208  22. Symfony\Component\DependencyInjection\Compiler\AutowirePass->createTypeAlternatives() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:404
1.2595   22289208  23. Symfony\Component\DependencyInjection\Compiler\AutowirePass->populateAvailableTypes() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:430
1.4249   25897960  24. Symfony\Component\DependencyInjection\Compiler\AutowirePass->populateAvailableType() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:322
1.4249   25897960  25. Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass() /path/to/project/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:336
1.4249   25898040  26. Symfony\Component\Config\Resource\ClassExistenceResource->isFresh() /path/to/project/vendor/symfony/dependency-injection/ContainerBuilder.php:353
1.4249   25898224  27. class_exists() /path/to/project/vendor/symfony/config/Resource/ClassExistenceResource.php:78
1.4249   25898320  28. spl_autoload_call() /path/to/project/vendor/symfony/config/Resource/ClassExistenceResource.php:78
1.4249   25898416  29. Symfony\Component\Debug\DebugClassLoader->loadClass() /path/to/project/vendor/symfony/config/Resource/ClassExistenceResource.php:78
1.4254   25923496  30. require('/path/to/project/vendor/doctrine/mongodb-odm-bundle/Form/DoctrineMongoDBTypeGuesser.php') /path/to/project/vendor/symfony/debug/DebugClassLoader.php:160

```

**Comment by alcaeus** [comment] 2019-07-09 18:11
I have a feeling that the root cause of this is the same as for https://github.com/doctrine/DoctrineBundle/issues/990. See https://github.com/symfony/symfony/issues/32395 for further discussion of this issue. Since unused services are expected to be dropped, I don't want to work around this for now. The next patch releases for PHP 7.2 and 7.3 will fix this behaviour once again (see https://github.com/php/php-src/commit/22ed362810c1b3a5ecb54ebd1d50d804c7fc3159). For PHP 7.4, we'll have to see what the recommendation from Symfony folks is: either it can be fixed in the DI component or we'll have to change our service configs to only load such services conditionally. Until then, I'm closing this issue.

**Closed by alcaeus** 2019-07-09 18:11 UTC
