### ISSUE TITLE
Symfony+mongodb+ODM get the records group by month , date format in db “2017-09-08”

### ISSUE THREAD

**Issue by Abhishekshukla02** [doctrine/DoctrineMongoDBBundle#428] opened 2017-09-09 12:44 UTC
Symfony query not working for mongodb+ODM, here is the query that i am using but something wrong to with the format.

$getRecordForMonth = $this->get('doctrine_mongodb.odm.default_aggregation_query') ->getCollection('AppBundle:project')->createAggregateQuery() ->group(['_id' => ['substr' => ['$createddt', 5, 2], 'count' => sum(1)]);

Here is the mongo query but while converting in symfony2,not able to do db.test.aggregate([ {$group: { _id: {$substr: ['$bookingdatetime', 5, 2]}, numberofbookings: {$sum: 1} }} ])

**Comment by malarzm** [comment] 2017-09-09 14:17
Closing as exact duplicate of [this StackOverflow post](https://stackoverflow.com/questions/46127831/symfonymongodbodm-get-the-records-group-by-month-date-format-in-db-2017-09). SO is correct way to seek usage help, please wait until somebody answers your question there.

**Closed by malarzm** 2017-09-09 14:17 UTC
